package com.echoenglish.app.playback

object PlaybackContract {
    const val ACTION_OPEN_PLAYER = "com.echoenglish.OPEN_PLAYER"
    const val ACTION_LOAD = "com.echoenglish.LOAD"
    const val ACTION_TOGGLE = "com.echoenglish.TOGGLE"
    const val ACTION_NEXT = "com.echoenglish.NEXT_SEGMENT"
    const val ACTION_PREVIOUS = "com.echoenglish.PREVIOUS_SEGMENT"
    const val ACTION_RESTART = "com.echoenglish.RESTART_SEGMENT"
    const val ACTION_SEEK = "com.echoenglish.SEEK_SEGMENT_RELATIVE"
    const val ACTION_SEEK_ABSOLUTE = "com.echoenglish.SEEK_ABSOLUTE"
    const val ACTION_SEEK_SEGMENT = "com.echoenglish.SEEK_SEGMENT"
    const val ACTION_UPDATE_SEGMENTS = "com.echoenglish.UPDATE_SEGMENTS"
    const val ACTION_UPDATE_REPEATS = "com.echoenglish.UPDATE_REPEATS"
    const val ACTION_UPDATE_GAP = "com.echoenglish.UPDATE_GAP"
    const val ACTION_UPDATE_SPEED = "com.echoenglish.UPDATE_SPEED"
    const val ACTION_TIMER = "com.echoenglish.TIMER"
    const val ACTION_CANCEL_TIMER = "com.echoenglish.CANCEL_TIMER"
    const val EXTRA_URI = "uri"
    const val EXTRA_MEDIA_ID = "media_id"
    const val EXTRA_TITLE = "title"
    const val EXTRA_STARTS = "starts"
    const val EXTRA_ENDS = "ends"
    const val EXTRA_TEXTS = "texts"
    const val EXTRA_CUE_STARTS = "cue_starts"
    const val EXTRA_CUE_ENDS = "cue_ends"
    const val EXTRA_CUE_TEXTS = "cue_texts"
    const val EXTRA_REPEATS = "repeats"
    const val EXTRA_GAP_MS = "segment_gap_ms"
    const val EXTRA_INDEX = "index"
    const val EXTRA_SPEED = "speed"
    const val EXTRA_POSITION = "position"
    const val EXTRA_DURATION = "duration"
    const val EXTRA_TIMER_MINUTES = "timer_minutes"
    const val EXTRA_STOP_AT_END = "stop_at_end"
}
